# Auto-generated with h2o

complete -c kill -s "1" -o "HUP" -d "Send signal HUP"
complete -c kill -s "2" -o "INT" -d "Send signal INT"
complete -c kill -s "3" -o "QUIT" -d "Send signal QUIT"
complete -c kill -s "4" -o "ILL" -d "Send signal ILL"
complete -c kill -s "5" -o "TRAP" -d "Send signal TRAP"
complete -c kill -s "6" -o "ABRT" -d "Send signal ABRT"
complete -c kill -s "7" -o "BUS" -d "Send signal BUS"
complete -c kill -s "8" -o "FPE" -d "Send signal FPE"
complete -c kill -s "9" -o "KILL" -d "Send signal KILL"
complete -c kill -o "10" -o "USR1" -d "Send signal USR1"
complete -c kill -o "11" -o "SEGV" -d "Send signal SEGV"
complete -c kill -o "12" -o "USR2" -d "Send signal USR2"
complete -c kill -o "13" -o "PIPE" -d "Send signal PIPE"
complete -c kill -o "14" -o "ALRM" -d "Send signal ALRM"
complete -c kill -o "15" -o "TERM" -d "Send signal TERM"
complete -c kill -o "16" -o "STKFLT" -d "Send signal STKFLT"
complete -c kill -o "17" -o "CHLD" -d "Send signal CHLD"
complete -c kill -o "18" -o "CONT" -d "Send signal CONT"
complete -c kill -o "19" -o "STOP" -d "Send signal STOP"
complete -c kill -o "20" -o "TSTP" -d "Send signal TSTP"
complete -c kill -o "21" -o "TTIN" -d "Send signal TTIN"
complete -c kill -o "22" -o "TTOU" -d "Send signal TTOU"
complete -c kill -o "23" -o "URG" -d "Send signal URG"
complete -c kill -o "24" -o "XCPU" -d "Send signal XCPU"
complete -c kill -o "25" -o "XFSZ" -d "Send signal XFSZ"
complete -c kill -o "26" -o "VTALRM" -d "Send signal VTALRM"
complete -c kill -o "27" -o "PROF" -d "Send signal PROF"
complete -c kill -o "28" -o "WINCH" -d "Send signal WINCH"
complete -c kill -o "29" -o "POLL" -d "Send signal POLL"
complete -c kill -o "30" -o "PWR" -d "Send signal PWR"
complete -c kill -o "31" -o "SYS" -d "Send signal SYS"
complete -c kill -s "s" -l "signal" -d "specify the <signal> to be sent" -x
complete -c kill -s "q" -l "queue" -d "integer value to be sent with the signal" -x
complete -c kill -s "l" -l "list" -d "list all signal names, or convert one to a name" -x
complete -c kill -s "L" -l "table" -d "list all signal names in a nice table"
complete -c kill -s "h" -l "help" -d "display this help and exit"
complete -c kill -s "V" -l "version" -d "output version information and exit"
