# Auto-generated with h2o

complete -c node  -d "script read from stdin (default if no file name is provided, interactive mode if a tty)"
complete -c node  -d "indicate the end of node options"
complete -c node -l "abort-on-uncaught-exception" -d "aborting instead of exiting causes a core file to be generated for analysis"
complete -c node -s "c" -l "check" -d "syntax check script without executing"
complete -c node -l "completion-bash" -d "print source-able bash completion script"
complete -c node -s "C" -l "conditions" -d "additional user conditions for conditional exports and imports" -x
complete -c node -l "cpu-prof" -d "Start the V8 CPU profiler on start up, and write the CPU profile to disk before exit."
complete -c node -l "cpu-prof-dir" -d "Directory where the V8 profiles generated by --cpu-prof will be placed." -r
complete -c node -l "cpu-prof-interval" -d "specified sampling interval in microseconds for the V8 CPU profile generated with --cpu-prof." -r
complete -c node -l "cpu-prof-name" -d "specified file name of the V8 CPU profile generated with --cpu-prof" -r
complete -c node -l "diagnostic-dir" -d "set dir for all output files (default: current working directory)" -r
complete -c node -l "disable-proto" -d "disable Object.prototype.__proto__" -x
complete -c node -l "disallow-code-generation-from-strings" -d "disallow eval and friends"
complete -c node -l "enable-fips" -d "enable FIPS crypto at startup"
complete -c node -l "enable-source-maps" -d "Source Map V3 support for stack traces"
complete -c node -s "e" -l "eval" -d "evaluate script" -x
complete -c node -l "experimental-import-meta-resolve" -d "experimental ES Module import.meta.resolve() support"
complete -c node -l "experimental-json-modules" -d "experimental JSON interop support for the ES Module loader"
complete -c node -l "loader" -l "experimental-loader" -d "use the specified module as a custom loader" -x
complete -c node -l "experimental-policy" -d "use the specified file as a security policy" -r
complete -c node -l "experimental-repl-await" -d "experimental await keyword support in REPL"
complete -c node -l "es-module-specifier-resolution" -l "experimental-specifier-resolution" -d "Select extension resolution algorithm for es modules; either 'explicit' (default) or 'node'" -x
complete -c node -l "experimental-vm-modules" -d "experimental ES Module support in vm module"
complete -c node -l "experimental-wasi-unstable-preview1" -d "experimental WASI support"
complete -c node -l "experimental-wasm-modules" -d "eexperimental ES Module support for webassembly modules"
complete -c node -l "force-context-aware" -d "disable loading non-context-aware addons"
complete -c node -l "force-fips" -d "force FIPS crypto (cannot be disabled)"
complete -c node -l "frozen-intrinsics" -d "experimental frozen intrinsics support"
complete -c node -l "heap-prof" -d "Start the V8 heap profiler on start up, and write the heap profile to disk before exit."
complete -c node -l "heap-prof-dir" -d "Directory where the V8 heap profiles generated by --heap-prof will be placed." -r
complete -c node -l "heap-prof-interval" -d "specified sampling interval in bytes for the V8 heap profile generated with --heap-prof." -r
complete -c node -l "heap-prof-name" -d "specified file name of the V8 heap profile generated with --heap-prof" -r
complete -c node -l "heapsnapshot-near-heap-limit" -d "Generate heap snapshots whenever V8 is approaching the heap limit." -x
complete -c node -l "heapsnapshot-signal" -d "Generate heap snapshot on specified signal" -x
complete -c node -s "h" -l "help" -d "print node command line options (currently set)"
complete -c node -l "huge-max-old-generation-size" -d "increase default maximum heap size on machines with 16GB memory or more"
complete -c node -l "icu-data-dir" -d "set ICU data load path to dir (overrides NODE_ICU_DATA) (note: linked-in ICU data is present)" -r
complete -c node -l "input-type" -d "set module type for string input" -x
complete -c node -l "insecure-http-parser" -d "use an insecure HTTP parser that accepts invalid HTTP headers"
complete -c node -l "inspect" -d "activate inspector on host:port (default: 127.0.0.1:9229)" -x
complete -c node -l "inspect-brk" -d "activate inspector on host:port and break at start of user script" -x
complete -c node -l "debug-port" -l "inspect-port" -d "set host:port for inspector" -x
complete -c node -l "inspect-publish-uid" -d "comma separated list of destinations for inspector uid(default: stderr,http)" -x
complete -c node -s "i" -l "interactive" -d "always enter the REPL even if stdin does not appear to be a terminal"
complete -c node -l "interpreted-frames-native-stack" -d "help system profilers to translate JavaScript interpreted frames"
complete -c node -l "jitless" -d "disable runtime allocation of executable memory"
complete -c node -l "max-http-header-size" -d "set the maximum size of HTTP headers (default: 16384 (16KB))" -x
complete -c node -l "no-deprecation" -d "silence deprecation warnings"
complete -c node -l "no-force-async-hooks-checks" -d "disable checks for async_hooks"
complete -c node -l "no-warnings" -d "silence all process warnings"
complete -c node -l "node-memory-debug" -d "Run with extra debug checks for memory leaks in Node.js itself"
complete -c node -l "openssl-config" -d "load OpenSSL configuration from the specified file (overrides OPENSSL_CONF)" -r
complete -c node -l "pending-deprecation" -d "emit pending deprecation warnings"
complete -c node -l "policy-integrity" -d "ensure the security policy contents match the specified integrity" -x
complete -c node -l "preserve-symlinks" -d "preserve symbolic links when resolving"
complete -c node -l "preserve-symlinks-main" -d "preserve symbolic links when resolving the main module"
complete -c node -s "p" -l "print" -d "evaluate script and print result" -x
complete -c node -l "prof" -d "Generate V8 profiler output."
complete -c node -l "prof-process" -d "process V8 profiler output generated using --prof"
complete -c node -l "redirect-warnings" -d "write warnings to file instead of stderr" -r
complete -c node -l "report-compact" -d "output compact single-line JSON"
complete -c node -l "report-directory" -l "report-dir" -d "define custom report pathname." -r
complete -c node -l "report-filename" -d "define custom report file name." -r
complete -c node -l "report-on-fatalerror" -d "generate diagnostic report on fatal (internal) errors"
complete -c node -l "report-on-signal" -d "generate diagnostic report upon receiving signals"
complete -c node -l "report-signal" -d "causes diagnostic report to be produced on provided signal, unsupported in Windows." -x
complete -c node -l "report-uncaught-exception" -d "generate diagnostic report on uncaught exceptions"
complete -c node -s "r" -l "require" -d "module to preload (option can be repeated)" -x
complete -c node -l "secure-heap" -d "total size of the OpenSSL secure heap" -x
complete -c node -l "secure-heap-min" -d "minimum allocation size from the OpenSSL secure heap" -x
complete -c node -l "throw-deprecation" -d "throw an exception on deprecations"
complete -c node -l "title" -d "the process title to use on startup" -x
complete -c node -l "tls-cipher-list" -d "use an alternative default TLS cipher list" -x
complete -c node -l "tls-keylog" -d "log TLS decryption keys to named file for traffic analysis" -r
complete -c node -l "tls-max-v1.2" -d "set default TLS maximum to TLSv1.2 (default: TLSv1.3)"
complete -c node -l "tls-max-v1.3" -d "set default TLS maximum to TLSv1.3 (default: TLSv1.3)"
complete -c node -l "tls-min-v1.0" -d "set default TLS minimum to TLSv1.0 (default: TLSv1.2)"
complete -c node -l "tls-min-v1.1" -d "set default TLS minimum to TLSv1.1 (default: TLSv1.2)"
complete -c node -l "tls-min-v1.2" -d "set default TLS minimum to TLSv1.2 (default: TLSv1.2)"
complete -c node -l "tls-min-v1.3" -d "set default TLS minimum to TLSv1.3 (default: TLSv1.2)"
complete -c node -l "trace-atomics-wait" -d "trace Atomics.wait() operations"
complete -c node -l "trace-deprecation" -d "show stack traces on deprecations"
complete -c node -l "trace-event-categories" -d "comma separated list of trace event categories to record" -x
complete -c node -l "trace-event-file-pattern" -d "Template string specifying the filepath for the trace-events data, it supports \${rotation} and \${pid}." -r
complete -c node -l "trace-exit" -d "show stack trace when an environment exits"
complete -c node -l "trace-sigint" -d "enable printing JavaScript stacktrace on SIGINT"
complete -c node -l "trace-sync-io" -d "show stack trace when use of sync IO is detected after the first tick"
complete -c node -l "trace-tls" -d "prints TLS packet trace information to stderr"
complete -c node -l "trace-uncaught" -d "show stack traces for the `throw` behind uncaught exceptions"
complete -c node -l "trace-warnings" -d "show stack traces on process warnings"
complete -c node -l "track-heap-objects" -d "track heap object allocations for heap snapshots"
complete -c node -l "unhandled-rejections" -d "define unhandled rejections behavior." -x
complete -c node -l "use-bundled-ca" -d "use bundled CA store (default)"
complete -c node -l "use-largepages" -d "Map the Node.js static code to large pages." -x
complete -c node -l "use-openssl-ca" -d "use OpenSSL's default CA store"
complete -c node -l "v8-options" -d "print V8 command line options"
complete -c node -l "v8-pool-size" -d "set V8's thread pool size" -x
complete -c node -s "v" -l "version" -d "print Node.js version"
complete -c node -l "zero-fill-buffers" -d "automatically zero-fill all newly allocated Buffer and SlowBuffer instances"
