# Auto-generated with h2o

complete -k -c npm -n __fish_use_subcommand -x -a whoami -d 'Display npm username'
complete -k -c npm -n __fish_use_subcommand -x -a view -d 'View registry info'
complete -k -c npm -n __fish_use_subcommand -x -a version -d 'Bump a package version'
complete -k -c npm -n __fish_use_subcommand -x -a update -d 'Update packages'
complete -k -c npm -n __fish_use_subcommand -x -a unstar -d 'Remove an item from your favorite packages'
complete -k -c npm -n __fish_use_subcommand -x -a unpublish -d 'Remove a package from the registry'
complete -k -c npm -n __fish_use_subcommand -x -a uninstall -d 'Remove a package'
complete -k -c npm -n __fish_use_subcommand -x -a token -d 'Manage your authentication tokens'
complete -k -c npm -n __fish_use_subcommand -x -a test -d 'Test a package'
complete -k -c npm -n __fish_use_subcommand -x -a team -d 'Manage organization teams and team memberships'
complete -k -c npm -n __fish_use_subcommand -x -a stop -d 'Stop a package'
complete -k -c npm -n __fish_use_subcommand -x -a start -d 'Start a package'
complete -k -c npm -n __fish_use_subcommand -x -a stars -d 'View packages marked as favorites'
complete -k -c npm -n __fish_use_subcommand -x -a star -d 'Mark your favorite packages'
complete -k -c npm -n __fish_use_subcommand -x -a shrinkwrap -d 'Lock down dependency versions for publication'
complete -k -c npm -n __fish_use_subcommand -x -a set-script -d 'Set tasks in the scripts section of package.json'
complete -k -c npm -n __fish_use_subcommand -x -a set -d 'Set a value in the npm configuration'
complete -k -c npm -n __fish_use_subcommand -x -a search -d 'Search for packages'
complete -k -c npm -n __fish_use_subcommand -x -a run-script -d 'Run arbitrary package scripts'
complete -k -c npm -n __fish_use_subcommand -x -a root -d 'Display npm root'
complete -k -c npm -n __fish_use_subcommand -x -a restart -d 'Restart a package'
complete -k -c npm -n __fish_use_subcommand -x -a repo -d 'Open package repository page in the browser'
complete -k -c npm -n __fish_use_subcommand -x -a rebuild -d 'Rebuild a package'
complete -k -c npm -n __fish_use_subcommand -x -a publish -d 'Publish a package'
complete -k -c npm -n __fish_use_subcommand -x -a prune -d 'Remove extraneous packages'
complete -k -c npm -n __fish_use_subcommand -x -a profile -d 'Change settings on your registry profile'
complete -k -c npm -n __fish_use_subcommand -x -a prefix -d 'Display prefix'
complete -k -c npm -n __fish_use_subcommand -x -a ping -d 'Ping npm registry'
complete -k -c npm -n __fish_use_subcommand -x -a pack -d 'Create a tarball from a package'
complete -k -c npm -n __fish_use_subcommand -x -a owner -d 'Manage package owners'
complete -k -c npm -n __fish_use_subcommand -x -a outdated -d 'Check for outdated packages'
complete -k -c npm -n __fish_use_subcommand -x -a org -d 'Manage orgs'
complete -k -c npm -n __fish_use_subcommand -x -a ls -d 'List installed packages'
complete -k -c npm -n __fish_use_subcommand -x -a logout -d 'Log out of the registry'
complete -k -c npm -n __fish_use_subcommand -x -a login -d 'Add a registry user account'
complete -k -c npm -n __fish_use_subcommand -x -a ll -d 'List installed packages'
complete -k -c npm -n __fish_use_subcommand -x -a link -d 'Symlink a package folder'
complete -k -c npm -n __fish_use_subcommand -x -a install-test -d 'Install package(s) and run tests'
complete -k -c npm -n __fish_use_subcommand -x -a install-ci-test -d 'Install a project with a clean slate and run tests'
complete -k -c npm -n __fish_use_subcommand -x -a install -d 'Install a package'
complete -k -c npm -n __fish_use_subcommand -x -a init -d 'Create a package.json file'
complete -k -c npm -n __fish_use_subcommand -x -a hook -d 'Manage registry hooks'
complete -k -c npm -n __fish_use_subcommand -x -a help -d 'Get help on npm'
complete -k -c npm -n __fish_use_subcommand -x -a get -d 'Get a value from the npm configuration'
complete -k -c npm -n __fish_use_subcommand -x -a fund -d 'Retrieve funding information'
complete -k -c npm -n __fish_use_subcommand -x -a find-dupes -d 'Find duplication in the package tree'
complete -k -c npm -n __fish_use_subcommand -x -a explore -d 'Browse an installed package'
complete -k -c npm -n __fish_use_subcommand -x -a explain -d 'Explain installed packages'
complete -k -c npm -n __fish_use_subcommand -x -a exec -d 'Run a command from a local or remote npm package'
complete -k -c npm -n __fish_use_subcommand -x -a edit -d 'Edit an installed package'
complete -k -c npm -n __fish_use_subcommand -x -a doctor -d 'Check your npm environment'
complete -k -c npm -n __fish_use_subcommand -x -a docs -d 'Open documentation for a package in a web browser'
complete -k -c npm -n __fish_use_subcommand -x -a dist-tag -d 'Modify package distribution tags'
complete -k -c npm -n __fish_use_subcommand -x -a diff -d 'The registry diff command'
complete -k -c npm -n __fish_use_subcommand -x -a deprecate -d 'Deprecate a version of a package'
complete -k -c npm -n __fish_use_subcommand -x -a dedupe -d 'Reduce duplication in the package tree'
complete -k -c npm -n __fish_use_subcommand -x -a config -d 'Manage the npm configuration files'
complete -k -c npm -n __fish_use_subcommand -x -a completion -d 'Tab Completion for npm'
complete -k -c npm -n __fish_use_subcommand -x -a ci -d 'Install a project with a clean slate'
complete -k -c npm -n __fish_use_subcommand -x -a cache -d 'Manipulates packages cache'
complete -k -c npm -n __fish_use_subcommand -x -a bugs -d 'Report bugs for a package in a web browser'
complete -k -c npm -n __fish_use_subcommand -x -a bin -d 'Display npm bin folder'
complete -k -c npm -n __fish_use_subcommand -x -a audit -d 'Run a security audit'
complete -k -c npm -n __fish_use_subcommand -x -a adduser -d 'Add a registry user account'
complete -k -c npm -n __fish_use_subcommand -x -a access -d 'Set access level on published packages'
