# Auto-generated with h2o

complete -c set -s "a" -d "Mark variables which are modified or created for export."
complete -c set -s "b" -d "Notify of job termination immediately."
complete -c set -s "e" -d "Exit immediately if a command exits with a non-zero status."
complete -c set -s "f" -d "Disable file name generation (globbing)."
complete -c set -s "h" -d "Remember the location of commands as they are looked up."
complete -c set -s "k" -d "All assignment arguments are placed in the environment for a command, not just those that precede the command name."
complete -c set -s "m" -d "Job control is enabled."
complete -c set -s "n" -d "Read commands but do not execute them."
complete -c set -s "o" -d "Set the variable corresponding to option-name:" -x
complete -c set -s "p" -d "Turned on whenever the real and effective user ids do not match."
complete -c set -s "t" -d "Exit after reading and executing one command."
complete -c set -s "u" -d "Treat unset variables as an error when substituting."
complete -c set -s "v" -d "Print shell input lines as they are read."
complete -c set -s "x" -d "Print commands and their arguments as they are executed."
complete -c set -s "B" -d "the shell will perform brace expansion"
complete -c set -s "C" -d "If set, disallow existing regular files to be overwritten by redirection of output."
complete -c set -s "E" -d "If set, the ERR trap is inherited by shell functions."
complete -c set -s "H" -d "Enable ! style history substitution."
complete -c set -s "P" -d "If set, do not resolve symbolic links when executing commands such as cd which change the current directory."
complete -c set -s "T" -d "If set, the DEBUG and RETURN traps are inherited by shell functions."
complete -c set  -d "Assign any remaining arguments to the positional parameters."
