name: configManta.py
description: configManta.py
usage: configManta.py [options]
options:
  - names:
      - --version
    argument: ""
    description: show program's version number and exit
  - names:
      - -h
      - --help
    argument: ""
    description: show this help message and exit
  - names:
      - --config
    argument: FILE
    description: provide a configuration file to override defaults in global config file
  - names:
      - --allHelp
    argument: ""
    description: show all extended/hidden options
  - names:
      - --bam
      - --normalBam
    argument: FILE
    description: Normal sample BAM or CRAM file. May be specified more than once, multiple inputs will be treated as each BAM file representing a different sample. [optional] (no default)
  - names:
      - --tumorBam
      - --tumourBam
    argument: FILE
    description: Tumor sample BAM or CRAM file. Only up to one tumor bam file accepted. [optional] (no default)
  - names:
      - --exome
    argument: ""
    description: 'Set options for WES input: turn off depth filters'
  - names:
      - --rna
    argument: ""
    description: Set options for RNA-Seq input. Must specify exactly one bam input file
  - names:
      - --unstrandedRNA
    argument: ""
    description: 'Set if RNA-Seq input is unstranded: Allows splice-junctions on either strand'
  - names:
      - --referenceFasta
    argument: FILE
    description: samtools-indexed reference fasta file [required]
  - names:
      - --runDir
    argument: DIR
    description: 'Name of directory to be created where all workflow scripts and output will be written. Each analysis requires a separate directory. (default: MantaWorkflow)'
  - names:
      - --callRegions
    argument: FILE
    description: 'Optionally provide a bgzip-compressed/tabix-indexed BED file containing the set of regions to call. No VCF output will be provided outside of these regions. The full genome will still be used to estimate statistics from the input (such as expected fragment size distribution). Only one BED file may be specified. (default: call the entire genome)'
version: 1.6.0
