name: vdb-config
description: vdb-config
usage: vdb-config [options] [<query> ...]
options:
  - names:
      - -a
      - --all
    argument: ""
    description: Print all information [default].
  - names:
      - -p
      - --cfg
    argument: ""
    description: Print current configuration.
  - names:
      - -f
      - --files
    argument: ""
    description: Print loaded files.
  - names:
      - -d
      - --load-path
    argument: ""
    description: Print load path.
  - names:
      - -e
      - --env
    argument: ""
    description: Print shell variables.
  - names:
      - -m
      - --modules
    argument: ""
    description: Print external modules.
  - names:
      - -s
      - --set
    argument: <name=value>
    description: Set configuration node value.
  - names:
      - -i
      - --interactive
    argument: ""
    description: Create/update configuration.
  - names:
      - --interactive-mode
    argument: <mode>
    description: 'Interactive mode: ''textual'' or ''graphical'' (default).'
  - names:
      - --restore-defaults
    argument: ""
    description: Create default or update existing user configuration.
  - names:
      - --ignore-protected-repositories
    argument: ""
    description: Stop printing warning message when protected repository is found.
  - names:
      - -o
      - --output
    argument: <x | n>
    description: 'Output type: one of (x n), where ''x'' is xml (default), ''n'' is native.'
  - names:
      - -Q
      - --simplified-quality-scores
    argument: <yes|no>
    description: 'yes: Prefer SRA Lite files with simplified base quality scores if available. no: Prefer SRA Normalized Format files with full base quality scores if available. Default: no.'
  - names:
      - -C
      - --cloud-info
    argument: ""
    description: Display cloud-releated information.
  - names:
      - --report-cloud-identity
    argument: <yes|no>
    description: Give permission to report cloud instance identity.
  - names:
      - --accept-aws-charges
    argument: <yes|no>
    description: Agree to accept charges for AWS usage.
  - names:
      - --set-aws-credentials
    argument: <path>
    description: Select file with AWS credentials.
  - names:
      - --set-aws-profile
    argument: <profile>
    description: Set AWS profile.
  - names:
      - --accept-gcp-charges
    argument: <yes|no>
    description: Agree to accept charges for GCP usage.
  - names:
      - --set-gcp-credentials
    argument: <path>
    description: Select file with GCP credentials.
  - names:
      - --prefetch-to-cwd
    argument: ""
    description: 'Prefetch downloads to current directory when public user repository is set (default: false).'
  - names:
      - --prefetch-to-user-repo
    argument: ""
    description: Prefetch downloads to public user repository when it is set (default).
  - names:
      - --proxy
    argument: <uri[:port]>
    description: Set HTTP proxy server configuration.
  - names:
      - --proxy-disable
    argument: <yes|no>
    description: Enable/disable using HTTP proxy.
  - names:
      - --cfg-dir
    argument: <path>
    description: Set directory to load configuration.
  - names:
      - --root
    argument: ""
    description: Enforce configuration update while being run by superuser.
  - names:
      - -h
      - --help
    argument: ""
    description: Output brief explanation for the program.
  - names:
      - -V
      - --version
    argument: ""
    description: Display the version of the program then quit.
  - names:
      - -L
      - --log-level
    argument: <level>
    description: Logging level as number or enum string. One of (fatal|sys|int|err|warn|info|debug) or (0-6) Current/default is warn
  - names:
      - -v
      - --verbose
    argument: ""
    description: Increase the verbosity of the program status messages. Use multiple times for more verbosity. Negates quiet.
  - names:
      - -q
      - --quiet
    argument: ""
    description: Turn off all status messages for the program. Negated by verbose.
  - names:
      - --option-file
    argument: <file>
    description: Read more options and parameters from the file.
subcommands:
  - name: vdb-config
    description: '[options] [<query> ...]'
    usage: vdb-config [options] [<query> ...]
    options:
      - names:
          - -a
          - --all
        argument: ""
        description: Print all information [default].
      - names:
          - -p
          - --cfg
        argument: ""
        description: Print current configuration.
      - names:
          - -f
          - --files
        argument: ""
        description: Print loaded files.
      - names:
          - -d
          - --load-path
        argument: ""
        description: Print load path.
      - names:
          - -e
          - --env
        argument: ""
        description: Print shell variables.
      - names:
          - -m
          - --modules
        argument: ""
        description: Print external modules.
      - names:
          - -s
          - --set
        argument: <name=value>
        description: Set configuration node value.
      - names:
          - -i
          - --interactive
        argument: ""
        description: Create/update configuration.
      - names:
          - --interactive-mode
        argument: <mode>
        description: 'Interactive mode: ''textual'' or ''graphical'' (default).'
      - names:
          - --restore-defaults
        argument: ""
        description: Create default or update existing user configuration.
      - names:
          - --ignore-protected-repositories
        argument: ""
        description: Stop printing warning message when protected repository is found.
      - names:
          - -o
          - --output
        argument: <x | n>
        description: 'Output type: one of (x n), where ''x'' is xml (default), ''n'' is native.'
      - names:
          - -C
          - --cloud-info
        argument: ""
        description: Display cloud-releated information.
      - names:
          - --accept-aws-charges
        argument: <yes | no>
        description: Agree to accept charges for AWS usage.
      - names:
          - --set-aws-credentials
        argument: <path>
        description: Select file with AWS credentials.
      - names:
          - --set-aws-profile
        argument: <profile>
        description: Set AWS profile.
      - names:
          - --accept-gcp-charges
        argument: <yes | no>
        description: Agree to accept charges for GCP usage.
      - names:
          - --set-gcp-credentials
        argument: <path>
        description: Select file with GCP credentials.
      - names:
          - --prefetch-to-cwd
        argument: ""
        description: 'Prefetch downloads to current directory when public user repository is set (default: false).'
      - names:
          - --prefetch-to-user-repo
        argument: ""
        description: Prefetch downloads to public user repository when it is set (default).
      - names:
          - --proxy
        argument: <uri[:port]>
        description: Set HTTP proxy server configuration.
      - names:
          - --proxy-disable
        argument: <yes | no>
        description: Enable/disable using HTTP proxy.
      - names:
          - --cfg-dir
        argument: <path>
        description: Set directory to load configuration.
      - names:
          - --root
        argument: ""
        description: Enforce configuration update while being run by superuser.
      - names:
          - -h
          - --help
        argument: ""
        description: Output brief explanation for the program.
      - names:
          - -V
          - --version
        argument: ""
        description: Display the version of the program then quit.
      - names:
          - -L
          - --log-level
        argument: <level>
        description: Logging level as number or enum string. One of (fatal|sys|int|err|warn|info|debug) or (0-6) Current/default is warn
      - names:
          - -v
          - --verbose
        argument: ""
        description: Increase the verbosity of the program status messages. Use multiple times for more verbosity. Negates quiet.
      - names:
          - -q
          - --quiet
        argument: ""
        description: Turn off all status messages for the program. Negated by verbose.
      - names:
          - --option-file
        argument: <file>
        description: Read more options and parameters from the file.
