name: ansible-config
description: View ansible configuration
usage: ansible-config [-h] [--version] [-v] {list,dump,view,init} ...
options:
  - names:
      - --version
    argument: ""
    description: show program's version number, config file location, configured module search path, module location, executable location and exit
  - names:
      - -h
      - --help
    argument: ""
    description: show this help message and exit
  - names:
      - -v
      - --verbose
    argument: ""
    description: Causes Ansible to print more debug messages. Adding multiple -v will increase the verbosity, the builtin plugins currently evaluate up to -vvvvvv. A reasonable level to start is -vvv, connection debugging might require -vvvv.
subcommands:
  - name: list
    description: Print all config options
    usage: ansible-config list [-h] [-v] [-c CONFIG_FILE] [-t {all,base,become,cache,callback,cliconf,connection,httpapi,inventory,lookup,netconf,shell,vars}] [--format {json,yaml}] [args ...]
    options:
      - names:
          - -h
          - --help
        argument: ""
        description: show this help message and exit
      - names:
          - -v
          - --verbose
        argument: ""
        description: Causes Ansible to print more debug messages. Adding multiple -v will increase the verbosity, the builtin plugins currently evaluate up to -vvvvvv. A reasonable level to start is -vvv, connection debugging might require -vvvv.
      - names:
          - -c
          - --config
        argument: CONFIG_FILE
        description: path to configuration file, defaults to first file found in precedence.
      - names:
          - -t
          - --type
        argument: '{all,base,become,cache,callback,cliconf,connection,httpapi,inventory,lookup,netconf,shell,vars}'
        description: Filter down to a specific plugin type.
      - names:
          - --format
          - -f
        argument: '{json,yaml}'
        description: Output format for list
  - name: dump
    description: Dump configuration
    usage: ansible-config dump [-h] [-v] [-c CONFIG_FILE] [-t {all,base,become,cache,callback,cliconf,connection,httpapi,inventory,lookup,netconf,shell,vars}] [--only-changed] [--format {json,yaml,display}] [args ...]
    options:
      - names:
          - -h
          - --help
        argument: ""
        description: show this help message and exit
      - names:
          - -v
          - --verbose
        argument: ""
        description: Causes Ansible to print more debug messages. Adding multiple -v will increase the verbosity, the builtin plugins currently evaluate up to -vvvvvv. A reasonable level to start is -vvv, connection debugging might require -vvvv.
      - names:
          - -c
          - --config
        argument: CONFIG_FILE
        description: path to configuration file, defaults to first file found in precedence.
      - names:
          - -t
          - --type
        argument: '{all,base,become,cache,callback,cliconf,connection,httpapi,inventory,lookup,netconf,shell,vars}'
        description: Filter down to a specific plugin type.
      - names:
          - --only-changed
          - --changed-only
        argument: ""
        description: Only show configurations that have changed from the default
      - names:
          - --format
          - -f
        argument: '{json,yaml,display}'
        description: Output format for dump
  - name: view
    description: View configuration file
    usage: ansible-config view [-h] [-v] [-c CONFIG_FILE] [-t {all,base,become,cache,callback,cliconf,connection,httpapi,inventory,lookup,netconf,shell,vars}] [args ...]
    options:
      - names:
          - -h
          - --help
        argument: ""
        description: show this help message and exit
      - names:
          - -v
          - --verbose
        argument: ""
        description: Causes Ansible to print more debug messages. Adding multiple -v will increase the verbosity, the builtin plugins currently evaluate up to -vvvvvv. A reasonable level to start is -vvv, connection debugging might require -vvvv.
      - names:
          - -c
          - --config
        argument: CONFIG_FILE
        description: path to configuration file, defaults to first file found in precedence.
      - names:
          - -t
          - --type
        argument: '{all,base,become,cache,callback,cliconf,connection,httpapi,inventory,lookup,netconf,shell,vars}'
        description: Filter down to a specific plugin type.
  - name: init
    description: Create initial configuration
    usage: ansible-config init [-h] [-v] [-c CONFIG_FILE] [-t {all,base,become,cache,callback,cliconf,connection,httpapi,inventory,lookup,netconf,shell,vars}] [--format {ini,env,vars}] [--disabled] [args ...]
    options:
      - names:
          - -h
          - --help
        argument: ""
        description: show this help message and exit
      - names:
          - -v
          - --verbose
        argument: ""
        description: Causes Ansible to print more debug messages. Adding multiple -v will increase the verbosity, the builtin plugins currently evaluate up to -vvvvvv. A reasonable level to start is -vvv, connection debugging might require -vvvv.
      - names:
          - -c
          - --config
        argument: CONFIG_FILE
        description: path to configuration file, defaults to first file found in precedence.
      - names:
          - -t
          - --type
        argument: '{all,base,become,cache,callback,cliconf,connection,httpapi,inventory,lookup,netconf,shell,vars}'
        description: Filter down to a specific plugin type.
      - names:
          - --format
          - -f
        argument: '{ini,env,vars}'
        description: Output format for init
      - names:
          - --disabled
        argument: ""
        description: Prefixes all entries with a comment character to disable them
version: ansible-config [core 2.14.0]
