name: conda-env
description: conda-env
options:
  - names:
      - -h
      - --help
    argument: ""
    description: Show this help message and exit.
subcommands:
  - name: create
    description: Create an environment based on an environment file
    options:
      - names:
          - -h
          - --help
        argument: ""
        description: Show this help message and exit.
      - names:
          - -f
          - --file
        argument: FILE
        description: 'environment definition file (default: environment.yml)'
      - names:
          - --force
        argument: ""
        description: force creation of environment (removing a previously existing environment of the same name).
      - names:
          - -d
          - --dry-run
        argument: ""
        description: Only display what would have been done.
      - names:
          - --no-default-packages
        argument: ""
        description: Ignore create_default_packages in the .condarc file.
      - names:
          - --experimental-solver
        argument: '{classic,libmamba,libmamba-draft}'
        description: EXPERIMENTAL. Choose which solver backend to use.
      - names:
          - -n
          - --name
        argument: ENVIRONMENT
        description: Name of environment.
      - names:
          - -p
          - --prefix
        argument: PATH
        description: Full path to environment location (i.e. prefix).
      - names:
          - -C
          - --use-index-cache
        argument: ""
        description: Use cache of channel index files, even if it has expired.
      - names:
          - -k
          - --insecure
        argument: ""
        description: Allow conda to perform "insecure" SSL connections and transfers. Equivalent to setting 'ssl_verify' to 'false'.
      - names:
          - --offline
        argument: ""
        description: Offline mode. Don't connect to the Internet.
      - names:
          - --json
        argument: ""
        description: Report all output as json. Suitable for using conda programmatically.
      - names:
          - -v
          - --verbose
        argument: ""
        description: Use once for info, twice for debug, three times for trace.
      - names:
          - -q
          - --quiet
        argument: ""
        description: Do not display progress bar.
  - name: export
    description: Export a given environment
    options:
      - names:
          - -h
          - --help
        argument: ""
        description: Show this help message and exit.
      - names:
          - -c
          - --channel
        argument: CHANNEL
        description: Additional channel to include in the export
      - names:
          - --override-channels
        argument: ""
        description: Do not include .condarc channels
      - names:
          - -f
          - --file
          - --no-builds
        argument: FILE
        description: Remove build specification from dependencies
      - names:
          - --ignore-channels
        argument: ""
        description: Do not include channel names with package names.
      - names:
          - --from-history
        argument: ""
        description: Build environment spec from explicit specs in history
      - names:
          - -n
          - --name
        argument: ENVIRONMENT
        description: Name of environment.
      - names:
          - -p
          - --prefix
        argument: PATH
        description: Full path to environment location (i.e. prefix).
      - names:
          - --json
        argument: ""
        description: Report all output as json. Suitable for using conda programmatically.
      - names:
          - -v
          - --verbose
        argument: ""
        description: Use once for info, twice for debug, three times for trace.
      - names:
          - -q
          - --quiet
        argument: ""
        description: Do not display progress bar.
  - name: list
    description: List the Conda environments
    options:
      - names:
          - -h
          - --help
        argument: ""
        description: Show this help message and exit.
      - names:
          - --json
        argument: ""
        description: Report all output as json. Suitable for using conda programmatically.
      - names:
          - -v
          - --verbose
        argument: ""
        description: Use once for info, twice for debug, three times for trace.
      - names:
          - -q
          - --quiet
        argument: ""
        description: Do not display progress bar.
  - name: remove
    description: Remove an environment
    options:
      - names:
          - -h
          - --help
        argument: ""
        description: Show this help message and exit.
      - names:
          - --experimental-solver
        argument: '{classic,libmamba,libmamba-draft}'
        description: EXPERIMENTAL. Choose which solver backend to use.
      - names:
          - -n
          - --name
        argument: ENVIRONMENT
        description: Name of environment.
      - names:
          - -p
          - --prefix
        argument: PATH
        description: Full path to environment location (i.e. prefix).
      - names:
          - -d
          - --dry-run
        argument: ""
        description: Only display what would have been done.
      - names:
          - --json
        argument: ""
        description: Report all output as json. Suitable for using conda programmatically.
      - names:
          - -q
          - --quiet
        argument: ""
        description: Do not display progress bar.
      - names:
          - -v
          - --verbose
        argument: ""
        description: Can be used multiple times. Once for INFO, twice for DEBUG, three times for TRACE.
      - names:
          - -y
          - --yes
        argument: ""
        description: Do not ask for confirmation.
  - name: update
    description: Update the current environment based on environment file
    options:
      - names:
          - -h
          - --help
        argument: ""
        description: Show this help message and exit.
      - names:
          - -f
          - --file
        argument: FILE
        description: 'environment definition (default: environment.yml)'
      - names:
          - --prune
        argument: ""
        description: remove installed packages not defined in environment.yml
      - names:
          - --experimental-solver
        argument: '{classic,libmamba,libmamba-draft}'
        description: EXPERIMENTAL. Choose which solver backend to use.
      - names:
          - -n
          - --name
        argument: ENVIRONMENT
        description: Name of environment.
      - names:
          - -p
          - --prefix
        argument: PATH
        description: Full path to environment location (i.e. prefix).
      - names:
          - --json
        argument: ""
        description: Report all output as json. Suitable for using conda programmatically.
      - names:
          - -v
          - --verbose
        argument: ""
        description: Use once for info, twice for debug, three times for trace.
      - names:
          - -q
          - --quiet
        argument: ""
        description: Do not display progress bar.
  - name: config
    description: Configure a conda environment
    options:
      - names:
          - -h
          - --help
        argument: ""
        description: Show this help message and exit.
