name: condax
description: condax
options:
  - names:
      - --help
    argument: ""
    description: Show this message and exit.
subcommands:
  - name: ensure-path
    description: Ensure the condax links directory is on $PATH.
    options:
      - names:
          - --help
        argument: ""
        description: Show this message and exit.
  - name: install
    description: Install a package with condax.
    options:
      - names:
          - -c
          - --channel
        argument: TEXT
        description: Use the channels specified to install. If not specified condax will default to using ['conda-forge', 'defaults'].
      - names:
          - --help
        argument: ""
        description: Show this message and exit.
  - name: remove
    description: Ensure the condax links directory is on $PATH.
    options:
      - names:
          - --help
        argument: ""
        description: Show this message and exit.
  - name: update
    description: Update package(s) installed by condax.
    options:
      - names:
          - --all
        argument: ""
        description: Set to update all packages installed by condax
      - names:
          - --help
        argument: ""
        description: Show this message and exit.
