name: ifconfig
description: configure a network interface
usage: |-
  ifconfig [-a] [-v] [-s] <interface> [[<AF>] <address>]
  [add <address>[/<prefixlen>]]
  [del <address>[/<prefixlen>]]
  [[-]broadcast [<address>]]  [[-]pointopoint [<address>]]
  [netmask <address>]  [dstaddr <address>]  [tunnel <address>]
  [outfill <NN>] [keepalive <NN>]
  [hw <HW> <address>]  [mtu <NN>]
  [[-]trailers]  [[-]arp]  [[-]allmulti]
  [multicast]  [[-]promisc]
  [mem_start <NN>]  [io_addr <NN>]  [irq <NN>]  [media <type>]
  [txqueuelen <NN>]
  [[-]dynamic]
  [up|down] ...
options:
  - names:
      - -a
    argument: ""
    description: display all interfaces which are currently available, even if down
  - names:
      - -s
    argument: ""
    description: display a short list (like netstat -i)
  - names:
      - -v
    argument: ""
    description: be more verbose for some error conditions
version: net-tools 2.10-alpha
tldr: |
  > Network Interface Configurator.
  > More information: <https://net-tools.sourceforge.io/man/ifconfig.8.html>.

  - View network settings of an Ethernet adapter:

  `ifconfig eth0`

  - Display details of all interfaces, including disabled interfaces:

  `ifconfig -a`

  - Disable eth0 interface:

  `ifconfig eth0 down`

  - Enable eth0 interface:

  `ifconfig eth0 up`

  - Assign IP address to eth0 interface:

  `ifconfig eth0 {{ip_address}}`
