name: pkg-config
description: pkg-config
options:
  - names:
      - --modversion
    argument: ""
    description: Requests that the version information of the libraries specified on the command line be displayed. If pkg-config can find all the libraries on the command line, each library's version string is printed to stdout, one version per line. In this case pkg-config exits successfully. If one or more libraries is unknown, pkg-config exits with a nonzero code, and the contents of stdout are undefined.
  - names:
      - --version
    argument: ""
    description: Displays the version of pkg-config and terminates.
  - names:
      - --atleast-pkgconfig-version
    argument: VERSION
    description: Requires at least the given version of pkg-config.
  - names:
      - --help
    argument: ""
    description: Displays a help message and terminates.
  - names:
      - --print-errors
    argument: ""
    description: If one or more of the modules on the command line, or their dependencies, are not found, or if an error occurs in parsing a .pc file, then this option will cause errors explaining the problem to be printed. With "predicate" options such as "--exists" pkg-config runs silently by default, because it's usually used in scripts that want to control what's output. This option can be used alone (to just print errors encountered locating modules on the command line) or with other options. The PKG_CONFIG_DEBUG_SPEW environment variable overrides this option.
  - names:
      - --short-errors
    argument: ""
    description: Print short error messages.
  - names:
      - --silence-errors
    argument: ""
    description: If one or more of the modules on the command line, or their dependencies, are not found, or if an error occurs in parsing a a .pc file, then this option will keep errors explaining the problem from being printed. With "predicate" options such as "--exists" pkg-config runs silently by default, because it's usually used in scripts that want to control what's output. So this option is only useful with options such as "--cflags" or "--modversion" that print errors by default. The PKG_CONFIG_DEBUG_SPEW environment variable overrides this option.
  - names:
      - --errors-to-stdout
    argument: ""
    description: If printing errors, print them to stdout rather than the default stderr
  - names:
      - --debug
    argument: ""
    description: Print debugging information. This is slightly different than the PKG_CONFIG_DEBUG_SPEW environment variable, which also enable "--print-errors".
  - names:
      - --cflags
    argument: ""
    description: This prints pre-processor and compile flags required to compile the packages on the command line, including flags for all their dependencies. Flags are "compressed" so that each identical flag appears only once. pkg-config exits with a nonzero code if it can't find metadata for one or more of the packages on the command line.
  - names:
      - --cflags-only-I
    argument: ""
    description: This prints the -I part of "--cflags". That is, it defines the header search path but doesn't specify anything else.
  - names:
      - --cflags-only-other
    argument: ""
    description: This prints parts of "--cflags" not covered by "--cflags-only-I".
  - names:
      - --libs
    argument: ""
    description: This option is identical to "--cflags", only it prints the link flags. As with "--cflags", duplicate flags are merged (maintaining proper ordering), and flags for dependencies are included in the output.
  - names:
      - --libs-only-L
    argument: ""
    description: This prints the -L/-R part of "--libs". That is, it defines the library search path but doesn't specify which libraries to link with.
  - names:
      - --libs-only-l
    argument: ""
    description: This prints the -l part of "--libs" for the libraries specified on the command line. Note that the union of "--libs-only-l" and "--libs-only-L" may be smaller than "--libs", due to flags such as -rdynamic.
  - names:
      - --libs-only-other
    argument: ""
    description: This prints the parts of "--libs" not covered by "--libs-only-L" and "--libs-only-l", such as "--pthread".
  - names:
      - --variable
    argument: VARIABLENAME
    description: 'This returns the value of a variable defined in a package''s .pc file. Most packages define the variable "prefix", for example, so you can say:'
  - names:
      - --define-variable
    argument: VARIABLENAME=VARIABLEVALUE
    description: 'This sets a global value for a variable, overriding the value in any .pc files. Most packages define the variable "prefix", for example, so you can say:'
  - names:
      - --print-variables
    argument: ""
    description: Returns a list of all variables defined in the package.
  - names:
      - --uninstalled
    argument: ""
    description: Normally if you request the package "foo" and the package "foo-uninstalled" exists, pkg-config will prefer the "-uninstalled" variant. This allows compilation/linking against uninstalled packages. If you specify the "--uninstalled" option, pkg-config will return successfully if any "-uninstalled" packages are being used, and return failure (false) otherwise. (The PKG_CONFIG_DISABLE_UNINSTALLED environment variable keeps pkg-config from implicitly choosing "-uninstalled" packages, so if that variable is set, they will only have been used if you pass a name like "foo-uninstalled" on the command line explicitly.)
  - names:
      - --max-version
    argument: VERSION
    description: These options test whether the package or list of packages on the command line are known to pkg-config, and optionally whether the version number of a package meets certain constraints. If all packages exist and meet the specified version constraints, pkg-config exits successfully. Otherwise it exits unsuccessfully. Only the first VERSION comparing option will be honored. Subsequent options of this type will be ignored.
  - names:
      - --validate
    argument: ""
    description: 'Checks the syntax of a package''s .pc file for validity. This is the same as --exists except that dependencies are not verified. This can be useful for package developers to test their .pc file prior to release:'
  - names:
      - --msvc-syntax
    argument: ""
    description: This option is available only on Windows. It causes pkg-config to output -l and -L flags in the form recognized by the Microsoft Visual C++ command-line compiler, cl. Specifically, instead of -Lx:/some/path it prints /libpath:x/some/path, and instead of -lfoo it prints foo.lib. Note that the --libs output consists of flags for the linker, and should be placed on the cl command line after a /link switch.
  - names:
      - --define-prefix
      - --dont-define-prefix
    argument: ""
    description: These options control whether pkg-config overrides the value of the variable prefix in each .pc file. With --define-prefix, pkg-config uses the installed location of the .pc file to determine the prefix. --dont-define-prefix prevents this behavior. The default is usually --define-prefix.
  - names:
      - --prefix-variable
    argument: PREFIX
    description: Set the name of the variable that pkg-config overrides instead of prefix when using the --define-prefix feature.
  - names:
      - --static
    argument: ""
    description: Output libraries suitable for static linking. That means including any private libraries in the output. This relies on proper tagging in the .pc files, else a too large number of libraries will ordinarily be output.
  - names:
      - --list-all
    argument: ""
    description: List all modules found in the pkg-config path.
  - names:
      - --print-provides
    argument: ""
    description: List all modules the given packages provides.
  - names:
      - --print-requires
    argument: ""
    description: List all modules the given packages requires.
  - names:
      - --print-requires-private
    argument: ""
    description: List all modules the given packages requires for static linking (see --static).
version: 0.29.1
tldr: |
  > Provide the details of installed libraries for compiling applications.
  > More information: <https://www.freedesktop.org/wiki/Software/pkg-config/>.

  - Get the list of libraries and their dependencies:

  `pkg-config --libs {{library1 library2 ...}}`

  - Get the list of libraries, their dependencies, and proper cflags for gcc:

  `pkg-config --cflags --libs {{library1 library2 ...}}`

  - Compile your code with libgtk-3, libwebkit2gtk-4.0 and all their dependencies:

  `c++ example.cpp $(pkg-config --cflags --libs gtk+-3.0 webkit2gtk-4.0) -o example`
