#!/usr/bin/env bash
#
# Create all.json.gz from json/*.json
#
#   $ ./make-gzip
#
# Require jq, ajv, parallel
#


# -u  Treat unset variables as an error when substituting.
# -e  Exit immediately if a command exits with a non-zero status.
# -x  Print commands and their arguments as they are executed.
# See `help set` in bash for more information.
set -uex

if [[ ! "$(command -v ajv)" ]]; then
    echo "[error] ajv is missing. Install ajv-cli via"
    echo "npm install -g ajv-cli"
    exit 1
fi

if [[ ! "$(command -v jq)" ]]; then
    echo "[error] jq is missing. Install jq to run this script."
    exit 1
fi

if [[ ! "$(command -v parallel)" ]]; then
    echo "[error] parallel is missing. Install parallel to run this script."
    exit 1
fi

basedir="$(dirname "$(readlink -f "$0")")"
rootdir="$basedir/.."

dirnames=(general bio)
for dir_ in ${dirnames[*]}; do
    # Make a list of command names available as json files
    "$basedir"/make-list "$dir_" > "$rootdir"/"$dir_".txt

    # Make gzipped file from a json array
    jq -cs . "$rootdir"/"$dir_"/json/*.json | gzip > "$rootdir"/"$dir_".json.gz
done
