#!/usr/bin/env bash
#
# Starting with YAML, make JSON, bash/zsh/fish, gzip, and command list txt files.
#
#   $ ./run bat
#
# Require jq, ajv, parallel
#

basedir="$(dirname "$(readlink -f "$0")")"
cmd="$1"
cd "$basedir"

yaml="$cmd.yaml"

if [[ -z "$(find .. -name "$yaml" -type f)" ]]; then
    echo "File not found: $cmd.yaml"
    exit 1
fi

if [[ ! "$(command -v ajv)" ]]; then
    echo "[error] ajv is missing. Install ajv-cli via"
    echo "npm install -g ajv-cli"
    exit 1
fi

if [[ ! "$(command -v jq)" ]]; then
    echo "[error] jq is missing. Install jq to run this script."
    exit 1
fi

if [[ ! "$(command -v yq)" ]]; then
    echo "[error] yq is missing. Install yq to run this script."
    exit 1
fi

if [[ ! "$(command -v parallel)" ]]; then
    echo "[error] parallel is missing. Install parallel to run this script."
    exit 1
fi

echo "🚀 Adding tldr if possible"
./addtldr "$cmd"

echo "🚀 Creating JSON"
./tojson "$cmd"

echo "🚀 Creating bash/zsh/fish"
parallel ./gen-shellcomp {} "$cmd" ::: bash zsh fish

echo "🚀 Done. Don't forget to update gzipped files."