#!/usr/bin/env bash
#
# Batch run tojson.sh s.t.
#
#   yaml/*.yaml  -->  json/*.json
#
# Usage:
#
#     $ ./tojson-batch general
#

set -o errexit
set -o nounset
set -o pipefail
if [[ "${TRACE-0}" == "1" ]]; then
    set -o xtrace
fi

basedir="$(dirname "$(readlink -f "$0")")"
dir="$1"


if [[ -z "$dir" ]] || [[ "${1-}" =~ ^-*h(elp)?$ ]]; then
    echo "Set directory as the argument."
    echo "Usage: ./tojson-batch {general|bio|experimental}"
    exit 1
fi


for f in "$basedir"/../"$dir"/yaml/*.yaml; do
    file="$(basename "$f")"
    name="${file%.*}"
    echo " ... creating ${name}.json in ${dir}/json"
    "$basedir"/tojson "$name"
done
