#!/usr/bin/env bash
#
# Use ajv to validate a JSON with a schema
#
# Example:
#   $ ./validate-json ../general/json/jq.json
#

# Require ajv
if [[ ! "$(command -v ajv)" ]]; then
    echo "[error] ajv is missing. Install ajv-cli via"
    echo "npm install -g ajv-cli"
    exit 1
fi

basedir="$(dirname "$(readlink -f "$0")")"
schema="$basedir"/../json-schema/command-2022-03-14.schema.json
ajv -s "$schema" -d "$1"
