on: [push]
name: validate json and create DB

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: |
          npm install -g ajv-cli
      - run: |
          scripts/createdb
      - uses: actions/upload-artifact@v4
        with:
          path: ./commandspecs.db
